use mavenmovies;

-- 1 --Retrieve the total number of rentals made in the Sakila database.

select * from payment;
select count(amount) from payment;
select count(rental_id),count(payment_id),count(amount) from payment;


-- 2 --Find the average rental duration (in days) of movies rented from the Sakila database.

select * from film;
select avg(rental_duration) from film;

-- 3 --Display the first name and last name of customers in uppercase. 

select * from customer;
select upper(first_name),upper(last_name),customer_id from customer;
 
-- 4 --Extract the month from the rental date and display it alongside the rental ID.

select * from rental;
select month(rental_date),rental_id from rental;

-- 5 --Retrieve the count of rentals for each customer (display customer ID and the count of rentals). 

select * from customer;
select * from payment;
select * from rental; 
select count(rental_id) from rental;
select distinct customer_id from rental;
select count(amount),rental_id from payment group by customer_id;
select count(rental_id),customer_id from rental group by customer_id;

-- 6 --Find the total revenue generated by each store.

select * from store;
select * from inventory;
select * from investor;
select * from payment;
select * from rental;
select * from staff;
 
 select store.store_id,sum(amount) as total from store 
 left join staff on store.store_id left join payment on staff.staff_id group by store.store_id ;


-- 7 --Display the title of the movie, customer's first name, and last name who rented it. 

select * from film;
select * from customer;
select * from rental;
select * from inventory;

select film.title as MovieName,customer.first_name as FirstName,customer.last_name as LastName from rental join inventory on rental.inventory_id=inventory.inventory_id 
join film on film.film_id=inventory.film_id join customer on rental.customer_id=customer.customer_id;

-- 8 --Retrieve the names of all actors who have appeared in the film "Gone with the Wind." 

select * from film where film.title like"Gone with the Wind";
select * from film_actor;
select * from actor;

select actor.first_name as ActorFirstName,actor.last_name as ActorLastName from actor join film_actor on film_actor.actor_id=actor.actor_id 
join film on film.film_id=film_actor.film_id where film.title like"Gone with the Wind"; 

-- 9 --Determine the total number of rentals for each category of movies.

select * from film;
select * from film_category;
select * from rental;
select * from inventory;

select film_category.category_id,count(*)as RentalCount from film_category join film on film.film_id=film_category.film_id 
join inventory on inventory.film_id=film_category.film_id join rental on rental.inventory_id=inventory.inventory_id group by film_category.category_id;
 
-- 10 --Find the average rental rate of movies in each language. 

select * from film;
select * from language;

select language.name as Language,avg(film.rental_rate) as AverageRate from film 
join language on film.language_id=language.language_id group by language.name;


-- 11 --Retrieve the customer names along with the total amount they've spent on rentals. 

select * from customer;
select * from payment;
select * from rental;

select customer.customer_id,customer.first_name,customer.last_name,sum(payment.amount) as TotalAmount from customer join payment on customer.customer_id=payment.customer_id
group by customer.customer_id,customer.first_name,customer.last_name;


-- 12 --List the titles of movies rented by each customer in a particular city (e.g., 'London').

select * from film;
select * from rental;
select * from inventory;
select * from customer;
select * from address;
select * from city; -- London

select customer.customer_id,customer.first_name,customer.last_name,city.city,film.title as MovieName from customer
join address on customer.address_id=address.address_id
join city on address.city_id=city.city_id
join rental on customer.customer_id=rental.customer_id
join inventory on rental.inventory_id=rental.inventory_id
join film on inventory.film_id=film.film_id
where city.city='London'
group by 
customer.customer_id,film.film_id,city.city;


-- 13 --Display the top 5 rented movies along with the number of times they've been rented. 

select * from film;
select * from rental;
select * from inventory;

select film.title as MovieName,count(rental.rental_id) as TotalRent from film
join inventory on film.film_id=inventory.film_id
join rental on inventory.inventory_id=rental.inventory_id
group by film.title
order by
TotalRent desc limit 5;

-- 14 --Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).

 select * from customer;
select * from rental;
select * from inventory;
select * from store;

select customer.customer_id,customer.first_name,customer.last_name from customer
join rental on customer.customer_id=rental.customer_id
join inventory on rental.inventory_id=inventory.inventory_id
join store on inventory.store_id=store.store_id
where store.store_id in(1,2)
group by
customer.customer_id,customer.first_name,customer.last_name
having 
count(distinct store.store_id)=2;